{"page":1,"results":[{"poster_path":"\/inVq3FRqcYIRl2la8iZikYYxFNR.jpg","adult":false,"overview":"Based upon Marvel Comics’ most unconventional anti-hero, DEADPOOL tells the origin story of former Special Forces operative turned mercenary Wade Wilson, who after being subjected to a rogue experiment that leaves him with accelerated healing powers, adopts the alter ego Deadpool. Armed with his new abilities and a dark, twisted sense of humor, Deadpool hunts down the man who nearly destroyed his life.","release_date":"2016-02-09","genre_ids":[28,12,35],"id":293660,"original_title":"Deadpool","original_language":"en","title":"Deadpool","backdrop_path":"\/n1y094tVDFATSzkTnFxoGZ1qNsG.jpg","popularity":52.15907,"vote_count":1841,"video":false,"vote_average":7.26},

{"poster_path":"\/kqjL17yufvn9OVLyXYpvtyrFfak.jpg","adult":false,"overview":"An apocalyptic story set in the furthest reaches of our planet, in a stark desert landscape where humanity is broken, and most everyone is crazed fighting for the necessities of life. Within this world exist two rebels on the run who just might be able to restore order. There's Max, a man of action and a man of few words, who seeks peace of mind following the loss of his wife and child in the aftermath of the chaos. And Furiosa, a woman of action and a woman who believes her path to survival may be achieved if she can make it across the desert back to her childhood homeland.","release_date":"2015-05-13","genre_ids":[878,53,28,12],"id":76341,"original_title":"Mad Max: Fury Road","original_language":"en","title":"Mad Max: Fury Road","backdrop_path":"\/tbhdm8UJAb4ViCTsulYFL3lxMCd.jpg","popularity":35.324309,"vote_count":4049,"video":false,"vote_average":7.43},

{"poster_path":"\/jjBgi2r5cRt36xF6iNUEhzscEcb.jpg","adult":false,"overview":"Twenty-two years after the events of Jurassic Park, Isla Nublar now features a fully functioning dinosaur theme park, Jurassic World, as originally envisioned by John Hammond.","release_date":"2015-06-09","genre_ids":[28,12,878,53],"id":135397,"original_title":"Jurassic World","original_language":"en","title":"Jurassic World","backdrop_path":"\/dkMD5qlogeRMiEixC4YNPUvax2T.jpg","popularity":24.833262,"vote_count":4066,"video":false,"vote_average":6.68},

{"poster_path":"\/5W794ugjRwYx6IdFp1bXJqqMWRg.jpg","adult":false,"overview":"In the 1820s, a frontiersman, Hugh Glass, sets out on a path of vengeance against those who left him for dead after a bear mauling.","release_date":"2015-12-25","genre_ids":[37,18,12,53],"id":281957,"original_title":"The Revenant","original_language":"en","title":"The Revenant","backdrop_path":"\/uS1SkjVviraGfFNgkDwe7ohTm8B.jpg","popularity":22.945537,"vote_count":1882,"video":false,"vote_average":7.27},

{"poster_path":"\/yUo6zAVRBRN6u76AaODDGh6gweJ.jpg","adult":false,"overview":"In the animal city of Zootopia, a fast-talking fox who's trying to make it big goes on the run when he's framed for a crime he didn't commit. Zootopia's top cop, a self-righteous rabbit, is hot on his tail, but when both become targets of a conspiracy, they're forced to team up and discover even natural enemies can become best friends.","release_date":"2016-02-12","genre_ids":[35,16,28,12,10751],"id":269149,"original_title":"Zootopia","original_language":"en","title":"Zootopia","backdrop_path":"\/16JyrAnJRGorH513skOCjRu1crR.jpg","popularity":21.724849,"vote_count":208,"video":false,"vote_average":7.22},

{"poster_path":"\/5aGhaIHYuQbqlHWvWYqMCnj40y2.jpg","adult":false,"overview":"During a manned mission to Mars, Astronaut Mark Watney is presumed dead after a fierce storm and left behind by his crew. But Watney has survived and finds himself stranded and alone on the hostile planet. With only meager supplies, he must draw upon his ingenuity, wit and spirit to subsist and find a way to signal to Earth that he is alive.","release_date":"2015-09-30","genre_ids":[18,12,878],"id":286217,"original_title":"The Martian","original_language":"en","title":"The Martian","backdrop_path":"\/sy3e2e4JwdAtd2oZGA2uUilZe8j.jpg","popularity":21.477644,"vote_count":2906,"video":false,"vote_average":7.57},

{"poster_path":"\/hE24GYddaxB9MVZl1CaiI86M3kp.jpg","adult":false,"overview":"A cryptic message from Bond’s past sends him on a trail to uncover a sinister organization. While M battles political forces to keep the secret service alive, Bond peels back the layers of deceit to reveal the terrible truth behind SPECTRE.","release_date":"2015-10-26","genre_ids":[28,12,80],"id":206647,"original_title":"Spectre","original_language":"en","title":"Spectre","backdrop_path":"\/wVTYlkKPKrljJfugXN7UlLNjtuJ.jpg","popularity":20.413252,"vote_count":2234,"video":false,"vote_average":6.27},

{"poster_path":"\/nN4cEJMHJHbJBsp3vvvhtNWLGqg.jpg","adult":false,"overview":"With the nation of Panem in a full scale war, Katniss confronts President Snow in the final showdown. Teamed with a group of her closest friends – including Gale, Finnick, and Peeta – Katniss goes off on a mission with the unit from District 13 as they risk their lives to stage an assassination attempt on President Snow who has become increasingly obsessed with destroying her. The mortal traps, enemies, and moral choices that await Katniss will challenge her more than any arena she faced in The Hunger Games.","release_date":"2015-11-18","genre_ids":[12,28,18],"id":131634,"original_title":"The Hunger Games: Mockingjay - Part 2","original_language":"en","title":"The Hunger Games: Mockingjay - Part 2","backdrop_path":"\/qjn3fzCAHGfl0CzeUlFbjrsmu4c.jpg","popularity":18.537091,"vote_count":1121,"video":false,"vote_average":6.9},

{"poster_path":"\/fqe8JxDNO8B8QfOGTdjh6sPCdSC.jpg","adult":false,"overview":"Bounty hunters seek shelter from a raging blizzard and get caught up in a plot of betrayal and deception.","release_date":"2015-12-25","genre_ids":[18,9648,53,37],"id":273248,"original_title":"The Hateful Eight","original_language":"en","title":"The Hateful Eight","backdrop_path":"\/sSvgNBeBNzAuKl8U8sP50ETJPgx.jpg","popularity":17.352982,"vote_count":1165,"video":false,"vote_average":7.32},

{"poster_path":"\/5JU9ytZJyR3zmClGmVm9q4Geqbd.jpg","adult":false,"overview":"The year is 2029. John Connor, leader of the resistance continues the war against the machines. At the Los Angeles offensive, John's fears of the unknown future begin to emerge when TECOM spies reveal a new plot by SkyNet that will attack him from both fronts; past and future, and will ultimately change warfare forever.","release_date":"2015-06-23","genre_ids":[878,28,53,12],"id":87101,"original_title":"Terminator Genisys","original_language":"en","title":"Terminator Genisys","backdrop_path":"\/bIlYH4l2AyYvEysmS2AOfjO7Dn8.jpg","popularity":17.233398,"vote_count":1857,"video":false,"vote_average":6.05},

{"poster_path":"\/ngKxbvsn9Si5TYVJfi1EGAGwThU.jpg","adult":false,"overview":"The true story of how The Boston Globe uncovered the massive scandal of child molestation and cover-up within the local Catholic Archdiocese, shaking the entire Catholic Church to its core.","release_date":"2015-11-06","genre_ids":[18,36,53],"id":314365,"original_title":"Spotlight","original_language":"en","title":"Spotlight","backdrop_path":"\/t3Oea7KbSpOvuqddMnlFtZ4WHn.jpg","popularity":15.713008,"vote_count":599,"video":false,"vote_average":7.7},

{"poster_path":"\/t5tGykRvvlLBULIPsAJEzGg1ylm.jpg","adult":false,"overview":"A father is without the means to pay for his daughter's medical treatment. As a last resort, he partners with a greedy co-worker to rob a casino. When things go awry they're forced to hijack a city bus.","release_date":"2015-11-13","genre_ids":[28,53],"id":336004,"original_title":"Heist","original_language":"en","title":"Heist","backdrop_path":"\/cBlnfR0n1GA2vPoUQNcbL9pb3VW.jpg","popularity":15.459578,"vote_count":116,"video":false,"vote_average":5.47},

{"poster_path":"\/vgAHvS0bT3fpcpnJqT6uDTUsHTo.jpg","adult":false,"overview":"Immediately after the events of The Desolation of Smaug, Bilbo and the dwarves try to defend Erebor's mountain of treasure from others who claim it: the men of the ruined Laketown and the elves of Mirkwood. Meanwhile an army of Orcs led by Azog the Defiler is marching on Erebor, fueled by the rise of the dark lord Sauron. Dwarves, elves and men must unite, and the hope for Middle-Earth falls into Bilbo's hands.","release_date":"2014-12-10","genre_ids":[12,14],"id":122917,"original_title":"The Hobbit: The Battle of the Five Armies","original_language":"en","title":"The Hobbit: The Battle of the Five Armies","backdrop_path":"\/qhH3GyIfAnGv1pjdV3mw03qAilg.jpg","popularity":15.397064,"vote_count":2493,"video":false,"vote_average":7.13},

{"poster_path":"\/yTdTuJww8NnL9YLaxL2LxDG5uQ7.jpg","adult":false,"overview":"A common thief joins a mythical god on a quest through Egypt.","release_date":"2016-02-25","genre_ids":[28,12,14],"id":205584,"original_title":"Gods of Egypt","original_language":"en","title":"Gods of Egypt","backdrop_path":"\/2s7uzOHQtOcP2fSoM9Loh4QKiTJ.jpg","popularity":15.087784,"vote_count":112,"video":false,"vote_average":4.42},

{"poster_path":"\/p11Ftd4VposrAzthkhF53ifYZRl.jpg","adult":false,"overview":"The men who made millions from a global economic meltdown.","release_date":"2015-12-11","genre_ids":[18,35],"id":318846,"original_title":"The Big Short","original_language":"en","title":"The Big Short","backdrop_path":"\/jmlMLYEsYY1kRc5qHIyTdxCeVmZ.jpg","popularity":14.630292,"vote_count":603,"video":false,"vote_average":7.31},

{"poster_path":"\/b9uYMMbm87IBFOq59pppvkkkgNg.jpg","adult":false,"overview":"After the sudden death of his beloved wife, John Wick receives one last gift from her, a beagle puppy named Daisy, and a note imploring him not to forget how to love. But John's mourning is interrupted when his 1969 Boss Mustang catches the eye of sadistic thug Iosef Tarasov who breaks into his house and steals it, beating John unconscious in the process. Unwittingly, he has just reawakened one of the most brutal assassins the underworld has ever known.","release_date":"2014-10-22","genre_ids":[28,53],"id":245891,"original_title":"John Wick","original_language":"en","title":"John Wick","backdrop_path":"\/mFb0ygcue4ITixDkdr7wm1Tdarx.jpg","popularity":14.092375,"vote_count":1827,"video":false,"vote_average":7.13},

{"poster_path":"\/nBNZadXqJSdt05SHLqgT0HuC5Gm.jpg","adult":false,"overview":"Interstellar chronicles the adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.","release_date":"2014-11-05","genre_ids":[12,18,878],"id":157336,"original_title":"Interstellar","original_language":"en","title":"Interstellar","backdrop_path":"\/xu9zaAevzQ5nnrsXN6JcahLnG4i.jpg","popularity":13.704834,"vote_count":4543,"video":false,"vote_average":8.21},

{"poster_path":"\/eqFckcHuFCT1FrzLOAvXBb4jHwq.jpg","adult":false,"overview":"Jack is a young boy of 5 years old who has lived all his life in one room. He believes everything within it are the only real things in the world. But what will happen when his Ma suddenly tells him that there are other things outside of Room?","release_date":"2015-10-16","genre_ids":[18],"id":264644,"original_title":"Room","original_language":"en","title":"Room","backdrop_path":"\/tBhp8MGaiL3BXpPCSl5xY397sGH.jpg","popularity":13.551557,"vote_count":493,"video":false,"vote_average":8.24},

{"poster_path":"\/fYzpM9GmpBlIC893fNjoWCwE24H.jpg","adult":false,"overview":"Thirty years after defeating the Galactic Empire, Han Solo and his allies face a new threat from the evil Kylo Ren and his army of Stormtroopers.","release_date":"2015-12-15","genre_ids":[28,12,878,14],"id":140607,"original_title":"Star Wars: The Force Awakens","original_language":"en","title":"Star Wars: The Force Awakens","backdrop_path":"\/njv65RTipNSTozFLuF85jL0bcQe.jpg","popularity":13.459923,"vote_count":3287,"video":false,"vote_average":7.72},

{"poster_path":"\/aBBQSC8ZECGn6Wh92gKDOakSC8p.jpg","adult":false,"overview":"Beatrice Prior must confront her inner demons and continue her fight against a powerful alliance which threatens to tear her society apart.","release_date":"2015-03-18","genre_ids":[878,53,12],"id":262500,"original_title":"Insurgent","original_language":"en","title":"Insurgent","backdrop_path":"\/L5QRL1O3fGs2hH1LbtYyVl8Tce.jpg","popularity":13.282605,"vote_count":1660,"video":false,"vote_average":6.57}],"total_results":258332,"total_pages":12917}')


{"page":1,"results":[{"poster_path":"\/811DjJTon9gD6hZ8nCjSitaIXFQ.jpg","adult":false,"overview":"A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy. Their concept catches on, with underground \"fight clubs\" forming in every town, until an eccentric gets in the way and ignites an out-of-control spiral toward oblivion.","release_date":"1999-10-14","genre_ids":[18],"id":550,"original_title":"Fight Club","original_language":"en","title":"Fight Club","backdrop_path":"\/8uO0gUM8aNqYLs1OsTBQiXu0fEv.jpg","popularity":6.212506,"vote_count":4459,"video":false,"vote_average":7.98}],"total_results":1,"total_pages":1}

{"page":1,"results":[{"poster_path":"\/lMHbadNmznKs5vgBAkHxKGHulOa.jpg","adult":false,"overview":"An ordinary Lego mini-figure, mistakenly thought to be the extraordinary MasterBuilder, is recruited to join a quest to stop an evil Lego tyrant from gluing the universe together.","release_date":"2014-02-06","genre_ids":[12,14,16,35,28,10751],"id":137106,"original_title":"The Lego Movie","original_language":"en","title":"The Lego Movie","backdrop_path":"\/wPRiV4TVpRCV2es81q0S1eRaUbm.jpg","popularity":3.029586,"vote_count":1878,"video":false,"vote_average":7.62},